language: java

jdk:
  - oraclejdk8

before_script:
  # This is required to avoid failures of HBase minicluster related to Hadoop 1.x releases
  - umask 022

after_success:
  - mvn coveralls:report maven-release-prepare maven-release-perform

after_failure:
  - cat client/target/surefire-reports/*.txt
  - cat server/target/surefire-reports/*.txt