language: java

jdk:
  - oraclejdk8

before_script:
  # This is required to avoid failures of HBase minicluster related to Hadoop 1.x releases
  - umask 022

script:
  - echo "NOOP"

after_success:
  - mvn cobertura:cobertura coveralls:report
  - mvn -B release:prepare release:perform deploy -DskipClean -DskipTests --settings sonatype-settings.xml

after_failure:
  - cat client/target/surefire-reports/*.txt
  - cat server/target/surefire-reports/*.txt

