language: java

notifications:
  email:
    - ikatkov@gmail.com

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  # This is required to avoid failures of HBase minicluster related to Hadoop 1.x releases
  - umask 022
  - git config --global user.email "ikatkov@gmail.com"
  - git config --global user.name "Igor Katkov"
  - git remote rm origin
  - git remote add origin https://ikatkov:7f4fafb8fd9142f55e7713a5fa075e840e8f578c@github.com/ikatkov/test.git

script:
  - echo "NOOP"

after_success:
  - mvn cobertura:cobertura coveralls:report
  - mvn -B release:prepare release:perform deploy -Pdeploy_profile --settings sonatype-settings.xml

after_failure:
  - cat client/target/surefire-reports/*.txt
  - cat server/target/surefire-reports/*.txt

